### PR TITLE
Remove Sendability from all Iterators

### PR DESCRIPTION
**Pull request by FranzBusch**
# Motivation
We have been discussing this a lot in the other PRs, but in general said that an `AsyncIterator` is the connection between the consuming task and the `AsyncSequence`. If an `AsyncIterator` would be `Sendable` then we don't have that relationship anymore. Therefore, no iterator of an `AsyncIterator` should be `Sendable`.

# Modification
Remove all `Sendable` conformances of the iterators even the conditional ones. We can always add them back later.

### CODE REVIEW

**Review by phausler — APPROVED** [review]
Looks good to me.

**Comment by phausler** [comment]
One follow on task; we should update the Sources/AsyncAlgorithms/AsyncAlgorithms.docc/Guides/Effects.md file to reflect this.

**Comment by FranzBusch** [comment]
@phausler Good catch! Updated the doc. Feel free to merge the PR

**Comment by ktoso** [comment]
🎉

**Pull request merged**
