### PR TITLE
Add a "new" proposal for AsyncBufferSequence

### PR DESCRIPTION
**Pull request by twittemb**
This outlines a proposal for the `AsyncBufferSequence` type used for buffering elements produced by an `AsyncSequence`.

@phausler I took the liberty of having me as an author but you should feel free to ask me to put you back as the author or co-author since you were the original one.

### CODE REVIEW

**Comment by phausler** [comment]
per the author bit; you definitely count as an author of things.

**Review by FranzBusch — APPROVED** [review]
LGTM!

**Comment by FranzBusch** [comment]
Let's get this re-pitched. @twittemb can you please create a new forum post for this?

**Comment by twittemb** [comment]
> Let's get this re-pitched. @twittemb can you please create a new forum post for this?

Will do

**Comment by twittemb** [comment]
> Let's get this re-pitched. @twittemb can you please create a new forum post for this?

https://forums.swift.org/t/swift-async-algorithms-proposal-buffer/63155

**Pull request merged**
