### PR TITLE
Add a proposal for AsyncBufferSequence

### PR DESCRIPTION
**Pull request by phausler**
This outlines a proposal for the `AsyncBufferSequence` type and the `AsyncBuffer` protocol used for buffering elements produced by an `AsyncSequence`

Read the full proposal [here](https://github.com/phausler/swift-async-algorithms/blob/pr/buffer_proposal/Evolution/NNNN-buffer.md)

### CODE REVIEW

**Review by Keithbreadley — APPROVED** [review]

**Comment by twittemb** [comment]
I guess we should update the proposal to reflect the new implementation, right?

**Comment by phausler** [comment]
yup that is definitely something that needs to be done, right now I've got refinements for `Observable` on my docket so once that is done I can get back around to updating it (unless someone else wants to modify and take that on)

**Comment by twittemb** [comment]
> yup that is definitely something that needs to be done, right now I've got refinements for `Observable` on my docket so once that is done I can get back around to updating it (unless someone else wants to modify and take that on)

I can give it a try. That way you will just to do a sanitization pass

**Comment by twittemb** [comment]
I guess this PR can be abandoned since the new buffer algorithm is merged?

**Comment by FranzBusch** [comment]
Yep closing it!

**Pull request closed without merging**
