### PR TITLE
Convert the guides for debounce and throttle into a proposal

### PR DESCRIPTION
**Pull request by phausler**
This proposal formalizes rate limiting algorithms for debouncing and throttling.

Read the full proposal [here](https://github.com/phausler/swift-async-algorithms/blob/1b7c4e9e63daa27aa7566c61980723d5b279031b/Evolution/NNNN-rate-limits.md)

### CODE REVIEW

**Comment by FranzBusch** [comment]
@phausler Debounce ought to implementable without requiring the iterator to be Sendable. Have we looked into this?

**Comment by phausler** [comment]
@FranzBusch the Sendable requirement definitely complicates the code considerably (again I think falls into the "this package should do it so other folks shouldn't" category). I am working on a version that reduces the task creation overhead and the sendable requirement to iterators.... but it makes the merge PR look simple in comparison... Sendable should be something part of the review. 

@twittemb Good call, I think half of that report is resolved now due to fixes in clock, I have not yet had a chance to verify other parts of it. The behavior should not be a full predication on reviewing this however.

**Comment by FranzBusch** [comment]
> @FranzBusch the Sendable requirement definitely complicates the code considerably (again I think falls into the "this package should do it so other folks shouldn't" category). I am working on a version that reduces the task creation overhead and the sendable requirement to iterators.... but it makes the merge PR look simple in comparison... Sendable should be something part of the review.

I am with you that it complicates things but we really should fix this since it has significant usability downsides. Like you said "let's get it right once in this package". Happy to help with this!

**Comment by phausler** [comment]
@swift-ci please test

**Pull request merged**
